plugins {
  id 'com.android.application'
}

android {

  namespace 'com.tbd.NetHack'
  compileSdk 35

  defaultConfig {
    applicationId 'com.tbd.NetHack'
    minSdk 21
    targetSdk 35
    versionName '3.6.7-1'
    versionCode 3671
  }

  compileOptions {
    sourceCompatibility JavaVersion.VERSION_17
    targetCompatibility JavaVersion.VERSION_17
  }

  lint {
    disable 'MissingClass'
  }

  sourceSets {
    main {
      manifest.srcFile 'AndroidManifest.xml'
      res.srcDirs = ['res']
      assets.srcDirs = ['assets']
      jniLibs.srcDirs = ['libs']
    }
  }
}

dependencies {
  implementation 'com.tbd.forkfront:lib:1.1'
}
